### PR TITLE
First part of the Java 8 + Maven refactor

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This PR makes the OVM3 hypervisor Maven compliant

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @borisroman @michaelandersen @miguelaferreira @bheuvel 

I already did the following tests:
- Cleaned the Maven repository
- Built the source
- Generated and Installed RPMs
- Deployed DC
- Deployed VM on isolated network

Will now run some integration tests. Will keep you updated.

**Comment by wilderrodrigues** [comment]
Ping @borisroman @michaelandersen @miguelaferreira @bheuvel 

I already did the following tests:
- Cleaned the Maven repository
- Built the source
- Generated and Installed RPMs
- Deployed DC
- Deployed VM on isolated network

Will now run some integration tests. Will keep you updated.

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
@wilderrodrigues I've removed the "[ovm3]" prefix from the title of the PR since it's in the name of the repo

**Comment by miguelaferreira** [comment]
go build

**Comment by wilderrodrigues** [comment]
Okay, @miguelaferreira

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
@wilderrodrigues for some reason when building it again, Maven did find the parent artefact. My guess is that we built the parent project at some point and that got stored in the .m2 repo. We need to get nexus up and running and have maven always pull the artefacts from there.

**Pull request merged**
